name: Pipeline de Seguridad DevSecOps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  sast:
    name: SAST - Semgrep
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 10

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Instalar Semgrep
        run: pip install semgrep

      # ✅ TODO completado
      - name: Ejecutar análisis SAST
        run: |
          semgrep --config p/python \
                  --config p/owasp-top-ten \
                  --config p/secrets \
                  --config p/sql-injection \
                  --error \
                  --json \
                  --output=semgrep-results.json \
                  Unidad_3_Seguridad_en_Aplicaciones_y_Datos/devsecops-lab/app/ || true
          semgrep --config p/python \
                  --config p/owasp-top-ten \
                  --config p/secrets \
                  --config p/sql-injection \
                  Unidad_3_Seguridad_en_Aplicaciones_y_Datos/devsecops-lab/app/

      - name: Guardar resultados SAST
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: semgrep-results
          path: semgrep-results.json


  sca:
    name: SCA - pip-audit
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # ✅ TODO completado
      - name: Instalar y ejecutar pip-audit
        run: |
          pip install pip-audit
          pip-audit -r Unidad_3_Seguridad_en_Aplicaciones_y_Datos/devsecops-lab/app/requirements.txt \
                    --format=json \
                    --output=audit-report.json || true
          echo '--- Reporte de CVEs ---'
          pip-audit -r Unidad_3_Seguridad_en_Aplicaciones_y_Datos/devsecops-lab/app/requirements.txt

      - name: Guardar reporte de auditoría
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pip-audit-report
          path: audit-report.json


  tests:
    name: Tests - pytest
    runs-on: ubuntu-latest
    needs: [ sast, sca ]
    timeout-minutes: 10

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # ✅ TODO completado
      - name: Instalar dependencias
        run: |
          pip install -r Unidad_3_Seguridad_en_Aplicaciones_y_Datos/devsecops-lab/app/requirements.txt
          pip install pytest

      - name: Ejecutar tests
        run: |
          pytest Unidad_3_Seguridad_en_Aplicaciones_y_Datos/devsecops-lab/tests/ -v
